### ISSUE TITLE
Output is always out.csv

### ISSUE THREAD

**Issue by JohnnyDP** [beenotung/csv-transpose#1]
Output is always named out.csv

Example:
If i run 
csv-transpose -i file.csv -o newFile.csv

Then the output file is named out.csv and not newFile.csv

**Comment by beenotung** [comment]
Thanks for reporting, I can confirm (reproduce) the bug.

I will fix it soon.

**Comment by beenotung** [comment]
The reported bug should have been fixed in csv-transpose@1.0.0.
@JohnnyDP , might you confirm that in your case? Thanks.

**Comment by JohnnyDP** [comment]
Yes it's working now.. Thank you very much!
